### ISSUE TITLE
内存池用完了，怎么处理？

### ISSUE THREAD

**Issue by xizhengchao** [beetlex-io/BeetleX#82]
[Warring] 127.0.0.1:41792 receive data error Create buffer error, maximum number of buffer pools!@   at BeetleX.Buffers.BufferPool.CreateBuffer() in E:\rider\20210821\App\BeetleX\Buffer
s\Pool.cs:line 228
   at BeetleX.Buffers.BufferPool.Pop() in E:\rider\20210821\App\BeetleX\Buffers\Pool.cs:line 247
   at BeetleX.TcpServer.BeginReceive(ISession session) in E:\rider\20210821\App\BeetleX\TcpServer.cs:line 471
出现这个错误，是在客户端反复用短连接压测的时候，用固定头的协议，如果在服务端，在不满足一些条件下，提前用CloseSession后，会出现这个错误，感觉是内存泄露造成的，一些内存估计有些地方push回收不了。一直是pop，所以造成这种。如果是发送在响应完整的走的话，没有这个问题的。

**Comment by beetlex-io** [comment]
根据需求配置ServerOptions
